/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TeamAuctionIdRouteImport } from './routes/team.$auctionId'
import { Route as AdminAuctionIdRouteImport } from './routes/admin.$auctionId'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuctionAuctionIdLiveRouteImport } from './routes/auction/$auctionId/live'
import { Route as AuctionAuctionIdLeaderboardRouteImport } from './routes/auction/$auctionId/leaderboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminAuctionIdTeamsRouteImport } from './routes/admin/$auctionId/teams'
import { Route as AdminAuctionIdSetupRouteImport } from './routes/admin/$auctionId/setup'
import { Route as AdminAuctionIdPlayersRouteImport } from './routes/admin/$auctionId/players'
import { Route as AdminAuctionIdControlRouteImport } from './routes/admin/$auctionId/control'
import { Route as ApiAuctionAuctionIdStreamRouteImport } from './routes/api/auction/$auctionId/stream'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamAuctionIdRoute = TeamAuctionIdRouteImport.update({
  id: '/team/$auctionId',
  path: '/team/$auctionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuctionIdRoute = AdminAuctionIdRouteImport.update({
  id: '/admin/$auctionId',
  path: '/admin/$auctionId',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuctionAuctionIdLiveRoute = AuctionAuctionIdLiveRouteImport.update({
  id: '/auction/$auctionId/live',
  path: '/auction/$auctionId/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionAuctionIdLeaderboardRoute =
  AuctionAuctionIdLeaderboardRouteImport.update({
    id: '/auction/$auctionId/leaderboard',
    path: '/auction/$auctionId/leaderboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuctionIdTeamsRoute = AdminAuctionIdTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminAuctionIdRoute,
} as any)
const AdminAuctionIdSetupRoute = AdminAuctionIdSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminAuctionIdRoute,
} as any)
const AdminAuctionIdPlayersRoute = AdminAuctionIdPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AdminAuctionIdRoute,
} as any)
const AdminAuctionIdControlRoute = AdminAuctionIdControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => AdminAuctionIdRoute,
} as any)
const ApiAuctionAuctionIdStreamRoute =
  ApiAuctionAuctionIdStreamRouteImport.update({
    id: '/api/auction/$auctionId/stream',
    path: '/api/auction/$auctionId/stream',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/admin/$auctionId': typeof AdminAuctionIdRouteWithChildren
  '/team/$auctionId': typeof TeamAuctionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$auctionId/control': typeof AdminAuctionIdControlRoute
  '/admin/$auctionId/players': typeof AdminAuctionIdPlayersRoute
  '/admin/$auctionId/setup': typeof AdminAuctionIdSetupRoute
  '/admin/$auctionId/teams': typeof AdminAuctionIdTeamsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auction/$auctionId/leaderboard': typeof AuctionAuctionIdLeaderboardRoute
  '/auction/$auctionId/live': typeof AuctionAuctionIdLiveRoute
  '/api/auction/$auctionId/stream': typeof ApiAuctionAuctionIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/admin/$auctionId': typeof AdminAuctionIdRouteWithChildren
  '/team/$auctionId': typeof TeamAuctionIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/$auctionId/control': typeof AdminAuctionIdControlRoute
  '/admin/$auctionId/players': typeof AdminAuctionIdPlayersRoute
  '/admin/$auctionId/setup': typeof AdminAuctionIdSetupRoute
  '/admin/$auctionId/teams': typeof AdminAuctionIdTeamsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auction/$auctionId/leaderboard': typeof AuctionAuctionIdLeaderboardRoute
  '/auction/$auctionId/live': typeof AuctionAuctionIdLiveRoute
  '/api/auction/$auctionId/stream': typeof ApiAuctionAuctionIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/admin/$auctionId': typeof AdminAuctionIdRouteWithChildren
  '/team/$auctionId': typeof TeamAuctionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$auctionId/control': typeof AdminAuctionIdControlRoute
  '/admin/$auctionId/players': typeof AdminAuctionIdPlayersRoute
  '/admin/$auctionId/setup': typeof AdminAuctionIdSetupRoute
  '/admin/$auctionId/teams': typeof AdminAuctionIdTeamsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auction/$auctionId/leaderboard': typeof AuctionAuctionIdLeaderboardRoute
  '/auction/$auctionId/live': typeof AuctionAuctionIdLiveRoute
  '/api/auction/$auctionId/stream': typeof ApiAuctionAuctionIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/$auctionId'
    | '/team/$auctionId'
    | '/admin/'
    | '/admin/$auctionId/control'
    | '/admin/$auctionId/players'
    | '/admin/$auctionId/setup'
    | '/admin/$auctionId/teams'
    | '/api/auth/$'
    | '/auction/$auctionId/leaderboard'
    | '/auction/$auctionId/live'
    | '/api/auction/$auctionId/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/$auctionId'
    | '/team/$auctionId'
    | '/admin'
    | '/admin/$auctionId/control'
    | '/admin/$auctionId/players'
    | '/admin/$auctionId/setup'
    | '/admin/$auctionId/teams'
    | '/api/auth/$'
    | '/auction/$auctionId/leaderboard'
    | '/auction/$auctionId/live'
    | '/api/auction/$auctionId/stream'
  id:
    | '__root__'
    | '/'
    | '/_guest'
    | '/_guest/login'
    | '/_guest/signup'
    | '/admin/$auctionId'
    | '/team/$auctionId'
    | '/admin/'
    | '/admin/$auctionId/control'
    | '/admin/$auctionId/players'
    | '/admin/$auctionId/setup'
    | '/admin/$auctionId/teams'
    | '/api/auth/$'
    | '/auction/$auctionId/leaderboard'
    | '/auction/$auctionId/live'
    | '/api/auction/$auctionId/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  AdminAuctionIdRoute: typeof AdminAuctionIdRouteWithChildren
  TeamAuctionIdRoute: typeof TeamAuctionIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AuctionAuctionIdLeaderboardRoute: typeof AuctionAuctionIdLeaderboardRoute
  AuctionAuctionIdLiveRoute: typeof AuctionAuctionIdLiveRoute
  ApiAuctionAuctionIdStreamRoute: typeof ApiAuctionAuctionIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$auctionId': {
      id: '/team/$auctionId'
      path: '/team/$auctionId'
      fullPath: '/team/$auctionId'
      preLoaderRoute: typeof TeamAuctionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$auctionId': {
      id: '/admin/$auctionId'
      path: '/admin/$auctionId'
      fullPath: '/admin/$auctionId'
      preLoaderRoute: typeof AdminAuctionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/auction/$auctionId/live': {
      id: '/auction/$auctionId/live'
      path: '/auction/$auctionId/live'
      fullPath: '/auction/$auctionId/live'
      preLoaderRoute: typeof AuctionAuctionIdLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/$auctionId/leaderboard': {
      id: '/auction/$auctionId/leaderboard'
      path: '/auction/$auctionId/leaderboard'
      fullPath: '/auction/$auctionId/leaderboard'
      preLoaderRoute: typeof AuctionAuctionIdLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$auctionId/teams': {
      id: '/admin/$auctionId/teams'
      path: '/teams'
      fullPath: '/admin/$auctionId/teams'
      preLoaderRoute: typeof AdminAuctionIdTeamsRouteImport
      parentRoute: typeof AdminAuctionIdRoute
    }
    '/admin/$auctionId/setup': {
      id: '/admin/$auctionId/setup'
      path: '/setup'
      fullPath: '/admin/$auctionId/setup'
      preLoaderRoute: typeof AdminAuctionIdSetupRouteImport
      parentRoute: typeof AdminAuctionIdRoute
    }
    '/admin/$auctionId/players': {
      id: '/admin/$auctionId/players'
      path: '/players'
      fullPath: '/admin/$auctionId/players'
      preLoaderRoute: typeof AdminAuctionIdPlayersRouteImport
      parentRoute: typeof AdminAuctionIdRoute
    }
    '/admin/$auctionId/control': {
      id: '/admin/$auctionId/control'
      path: '/control'
      fullPath: '/admin/$auctionId/control'
      preLoaderRoute: typeof AdminAuctionIdControlRouteImport
      parentRoute: typeof AdminAuctionIdRoute
    }
    '/api/auction/$auctionId/stream': {
      id: '/api/auction/$auctionId/stream'
      path: '/api/auction/$auctionId/stream'
      fullPath: '/api/auction/$auctionId/stream'
      preLoaderRoute: typeof ApiAuctionAuctionIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

interface AdminAuctionIdRouteChildren {
  AdminAuctionIdControlRoute: typeof AdminAuctionIdControlRoute
  AdminAuctionIdPlayersRoute: typeof AdminAuctionIdPlayersRoute
  AdminAuctionIdSetupRoute: typeof AdminAuctionIdSetupRoute
  AdminAuctionIdTeamsRoute: typeof AdminAuctionIdTeamsRoute
}

const AdminAuctionIdRouteChildren: AdminAuctionIdRouteChildren = {
  AdminAuctionIdControlRoute: AdminAuctionIdControlRoute,
  AdminAuctionIdPlayersRoute: AdminAuctionIdPlayersRoute,
  AdminAuctionIdSetupRoute: AdminAuctionIdSetupRoute,
  AdminAuctionIdTeamsRoute: AdminAuctionIdTeamsRoute,
}

const AdminAuctionIdRouteWithChildren = AdminAuctionIdRoute._addFileChildren(
  AdminAuctionIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  AdminAuctionIdRoute: AdminAuctionIdRouteWithChildren,
  TeamAuctionIdRoute: TeamAuctionIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AuctionAuctionIdLeaderboardRoute: AuctionAuctionIdLeaderboardRoute,
  AuctionAuctionIdLiveRoute: AuctionAuctionIdLiveRoute,
  ApiAuctionAuctionIdStreamRoute: ApiAuctionAuctionIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
